/* tool-canadian-c-spine-rule · ELUCENIA · https://github.com/Elucenia/tool-canadian-c-spine-rule
   Copyright (c) 2026 ELUCENIA · Felipe Guedes (fgxdev.com). Licensed under the Apache License 2.0: keep this notice and the NOTICE file, and mark your changes.
   Standalone integration. Package metadata and rights: README.md. */
(function(root){'use strict';
function freeze(value){if(value&&typeof value==='object'){for(const item of Object.values(value))freeze(item);Object.freeze(value);}return value;}
const TOOL=freeze({"id":"canadian-c-spine-rule","title":"Canadian C-Spine Rule","fields":[["excl","Critério de exclusão: &lt; 16 anos, Glasgow &lt; 15, sinais vitais anormais, trauma há mais de 48 h, trauma penetrante, paralisia aguda, doença vertebral conhecida ou cirurgia cervical prévia","chk",{"pts":0}],["idade65","<strong>Alto risco:</strong> idade ≥ 65 anos","chk",{"pts":0}],["mecanismo","<strong>Alto risco:</strong> mecanismo perigoso (queda de ≥ 0,9 m ou 5 degraus, carga axial na cabeça, colisão em alta velocidade, capotamento ou ejeção, veículo recreativo motorizado, colisão de bicicleta)","chk",{"pts":0}],["parestesia","<strong>Alto risco:</strong> parestesias nas extremidades","chk",{"pts":0}],["colisao","<strong>Baixo risco:</strong> colisão traseira simples","chk",{"pts":0}],["sentado","<strong>Baixo risco:</strong> sentado na sala de emergência","chk",{"pts":0}],["deambulou","<strong>Baixo risco:</strong> deambulou em algum momento após o trauma","chk",{"pts":0}],["tardia","<strong>Baixo risco:</strong> dor cervical de início tardio","chk",{"pts":0}],["semdor","<strong>Baixo risco:</strong> sem dor à palpação na linha média cervical","chk",{"pts":0}],["rot","Consegue rodar ativamente o pescoço 45° para a direita e para a esquerda?","radio",{"opts":{"0":"Não","1":"Sim","na":"Ainda não testado"}}]],"config":null,"reviewStatus":"restricted","clinicalValidation":"not-performed"});
function calculate(){return {error:'Cálculo suspenso: consulte a revisão e a fonte oficial.',code:'REVIEW_REQUIRED',id:TOOL.id};}
const api=Object.freeze({metadata:TOOL,calculate});if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.EluceniaTool=api;
})(typeof globalThis!=='undefined'?globalThis:this);
